version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: online_games_db
    restart: always
    environment:
      POSTGRES_USER: v3_user
      POSTGRES_PASSWORD: v3_password
      POSTGRES_DB: v3_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
